### ISSUE TITLE
Can´t get example to work

### ISSUE THREAD

**Issue by mzeyen** [paypal/nemo-example-app#8]
Hi,

i am new to nemo and first wanted to take a look at the example app. But i can´t get it to work.

I followed the step on how to install it start it and then tried "grunt automation" but unfortunately I get the following error:

 Running "loopmocha:local" (loopmocha) task
[grunt-loop-mocha] setting ENV var  nemoData with value { autoBaseDir: '/tmp/nemo2/nemo-example-app/test/functional',
  targetBrowser: 'firefox',
  localServer: true,
  targetBaseUrl: 'http://localhost:8000',
  seleniumJar: '/usr/local/bin/selenium-server-standalone-2.45.0.jar' }
[grunt-loop-mocha] iteration:  1427726667168-default
[grunt-loop-mocha] mocha argv:  --timeout,600000,--reporter,spec,/tmp/nemo2/nemo-example-app/test/functional/spec/basic-spec.js,/tmp/nemo2/nemo-example-app/test/functional/spec/cookie-spec.js,/tmp/nemo2/nemo-example-app/test/functional/spec/view-spec.js

  basic @nemoSuite@featureGroup1@

    1) "before all" hook

  0 passing (53ms)

  1 failing

  1) basic @nemoSuite@featureGroup1@ "before all" hook:
     Uncaught Error: spawn ENOENT
      at errnoException (child_process.js:1011:11)
      at Process.ChildProcess._handle.onexit (child_process.js:802:34)

Has this something to do with the "nemo namspace" problem in the nemo-mocha-factory? But this is fixed already and should be within this version (0.3.0).

Regards, 
Maik

**Comment by grawk** [comment]
Hi Maik,

Thanks for taking the time to file this issue.

Since you are new to nemo, may I please recommend that you use the newer nemo@1.0 pattern? We have already published the 1.0 modules, and are just bringing all the docs/examples into line for the round of "public relations" to announce it.

Currently, the nemo-example-app is using 1.0 at this branch:
https://github.com/paypal/nemo-example-app/tree/1.0-develop

Can you try to clone again, using the `1.0-develop` branch and then report any error message encountered?

Thanks!

**Comment by grawk** [comment]
closing due to inactivity
